notifications:
  recipients:
    - hatohol-commit@lists.sourceforge.net
language: cpp
compiler:
  - gcc
  - clang
install:
  - curl https://raw.github.com/clear-code/cutter/master/data/travis/setup.sh | sh
  - sudo apt-get install -qq -y autotools-dev libglib2.0-dev libjson-glib-dev libsoup2.4-dev libmysqlclient-dev sqlite3 ndoutils-nagios3-mysql uuid-dev npm
  - mysql -u root -e "GRANT all on ndoutils.* TO ndoutils@localhost IDENTIFIED BY 'admin';"
  - npm install -g mocha
  - npm install -g expect.js
before_script:
  - ./autogen.sh
  - ./configure
  - sudo chmod +r /var/log/syslog
  - sudo chmod 777 /var/run
script:
  - pushd .
  - ./server/mlpl/test/run-test.sh
  - cd server/test && ./run-test.sh
  - popd; pushd .
  - cd server/tools/test && ./run-test.sh
  - popd; pushd .
  - cd client; make static/js/hatohol_def.js && cd test; make && cd node; ./run-test.sh
