notifications:
  recipients:
#    - foobar@example.com
language: cpp
compiler:
  - gcc
  - clang
install:
  - curl https://raw.github.com/clear-code/cutter/master/data/travis/setup.sh | sh
  - sudo apt-get install -qq -y autotools-dev libglib2.0-dev
before_script:
  - ./autogen.sh
  - ./configure
script:
  - test/run-test.sh
